-- ============================================================================
--  COMERCIAL E TRIAGEM DENTRO DO CRM
--  Fatia 1 da absorcao do Sistema de Analise de Credito (07/09/2026)
--
--  O que esta fatia cobre, na ordem do dia a dia:
--    1. O Diretor Comercial sobe o e-mail (.msg/.eml) para dentro do CRM  -> `casos`
--    2. Triagem + agente conferem os documentos                           -> `caso_documentos`
--    3. O checklist diz o que falta                                       -> `caso_itens`
--    4. Concluido, nasce o cadastro unico do tomador                      -> `casos.tomador_id`
--
--  ADITIVO: nao altera nenhuma tabela existente, nao apaga nada.
--  O arquivo em si continua em `anexos` + Storage `fam-anexos` (fonte unica de
--  arquivo do CRM); `caso_documentos` guarda a LEITURA daquele arquivo, nao o arquivo.
--
--  DECISAO QUE VEIO DO SISTEMA ATUAL, e que nao pode se perder:
--  a SITUACAO do cadastro (pendente/bloqueado/em_conferencia/aprovado) NAO e
--  gravada em coluna nenhuma. Ela e sempre derivada dos itens, como no
--  `situacaoCadastro()` do motor. Gravar os dois abre a porta para item e
--  situacao discordarem, e ai ninguem sabe qual esta certo.
-- ============================================================================

-- ── 1. O caso: um e-mail que o Comercial trouxe para dentro ─────────────────
create table if not exists public.casos (
  id                      uuid primary key default gen_random_uuid(),
  numero                  bigint generated by default as identity,

  -- entrada (o que o Comercial subiu)
  assunto                 text not null,
  remetente_nome          text,
  remetente_email         text,
  recebido_em             timestamptz,
  corpo                   text,
  email_storage_path      text,

  -- identificacao (o que a triagem apurou; nunca sobrescreve decisao humana)
  cnpj                    text,
  razao_social            text,
  razao_social_confiavel  boolean not null default false,
  corretora_texto         text,
  corretora_id            uuid references public.corretoras(id) on delete set null,
  produto                 text,
  identificado_por        text not null default 'robo'
                          check (identificado_por in ('robo','humano','receita')),

  -- vinculos (nascem no fim da triagem)
  tomador_id              uuid references public.tomadores(id) on delete set null,
  operacao_id             uuid references public.operacoes(id) on delete set null,

  -- esteira
  etapa                   text not null default 'comercial'
                          check (etapa in ('comercial','triagem','analise','encerrado','descartado')),
  enviado_analise_em      timestamptz,
  encerrado_em            timestamptz,
  motivo_descarte         text,

  -- carimbo da triagem (mesmo conceito do hash_documentos do motor: um so,
  -- calculado num lugar so, para saber se a pasta mudou desde a ultima leitura)
  hash_documentos         text,
  versao_triagem          integer,
  triado_em               timestamptz,

  -- rastro
  criado_por_auth_id      uuid,
  criado_por_nome         text,
  criado_em               timestamptz not null default now(),
  atualizado_em           timestamptz not null default now(),
  observacao              text
);

comment on table public.casos is
  'Um caso por e-mail que o Comercial sobe para o CRM. E o container da entrada ate virar cadastro de tomador. Nao confundir com o tomador: varios casos podem apontar para a mesma empresa ao longo do tempo, e a chave da empresa continua sendo o CNPJ em `tomadores`.';
comment on column public.casos.hash_documentos is
  'Carimbo do conjunto de documentos do caso (sha256 curto). Igual mudou, a triagem precisa rodar de novo.';
comment on column public.casos.versao_triagem is
  'Versao do classificador que produziu esta leitura. Faz parte da chave de cache: conserto de regra tem que alcancar caso ja triado.';

create index if not exists casos_etapa_idx    on public.casos (etapa, criado_em desc);
create index if not exists casos_cnpj_idx     on public.casos (cnpj) where cnpj is not null;
create index if not exists casos_tomador_idx  on public.casos (tomador_id) where tomador_id is not null;

-- ── 2. O que a triagem leu de cada arquivo ──────────────────────────────────
create table if not exists public.caso_documentos (
  id                 uuid primary key default gen_random_uuid(),
  caso_id            uuid not null references public.casos(id) on delete cascade,
  anexo_id           uuid references public.anexos(id) on delete set null,

  nome               text not null,
  classe             text not null default 'outro'
                     check (classe in ('contabil','serasa_pj','serasa_pf','contrato_social',
                                       'acordo_socios','cartao_cnpj','outro')),
  certeza            text not null default 'baixa'
                     check (certeza in ('alta','media','baixa','nula')),
  nao_lido           boolean not null default false,
  sem_contas         boolean not null default false,
  anos               integer[] not null default '{}',
  detalhe            text,
  bytes              bigint,
  hash16             text,
  classificado_por   text not null default 'robo'
                     check (classificado_por in ('robo','humano')),
  criado_em          timestamptz not null default now()
);

comment on table public.caso_documentos is
  'A LEITURA de cada arquivo do caso (classe, certeza, anos encontrados). O arquivo em si mora em `anexos` + Storage. Arquivo ilegivel entra aqui com nao_lido=true em vez de sumir calado.';

create index if not exists caso_documentos_caso_idx on public.caso_documentos (caso_id);

-- ── 3. O checklist: o que a politica exige ──────────────────────────────────
create table if not exists public.caso_item_catalogo (
  id           text primary key,
  nome         text not null,
  exigencia    text not null default 'sinaliza' check (exigencia in ('bloqueia','sinaliza')),
  frase_falta  text,
  ordem        integer not null default 99,
  ativo        boolean not null default true
);

comment on table public.caso_item_catalogo is
  'O catalogo do que a FAM exige por caso. E tabela, e nao codigo, porque a politica de credito muda sem deploy (mesmo padrao de status_fluxo_tomador).';

insert into public.caso_item_catalogo (id, nome, exigencia, frase_falta, ordem) values
  ('demonstracoes_2_exercicios', 'Demonstrativos contabeis dos dois ultimos anos', 'bloqueia', 'A esteira para.', 1),
  ('serasa_pj',                  'Serasa do tomador',                              'bloqueia', 'O processo para.', 2),
  ('contrato_social',            'Contrato social',                                'sinaliza', 'A analise sai assim mesmo.', 3),
  ('demonstracao_ano_corrente',  'Demonstrativo financeiro do ano corrente',       'sinaliza', 'Apenas sinaliza.', 4)
on conflict (id) do nothing;

create table if not exists public.caso_itens (
  id           uuid primary key default gen_random_uuid(),
  caso_id      uuid not null references public.casos(id) on delete cascade,
  item         text not null references public.caso_item_catalogo(id),
  situacao     text not null default 'faltando'
               check (situacao in ('ok','faltando','duvida','a_caminho','dispensado')),
  por          text not null default 'robo' check (por in ('robo','humano')),
  detalhe      text,
  alerta       text,
  arquivos     text[] not null default '{}',
  anos         integer[] not null default '{}',
  obs          text,
  decidido_em  timestamptz,
  decidido_por text,
  unique (caso_id, item)
);

comment on table public.caso_itens is
  'Uma linha por exigencia do catalogo, por caso. Item marcado por humano (por=humano) NUNCA e sobrescrito pelo robo: ele so cai sozinho quando o documento aparece de verdade.';

-- ── 4. RLS ──────────────────────────────────────────────────────────────────
-- Leitura: todo mundo autenticado (a equipe acompanha o trabalho acontecer).
-- Escrita: quem ja tem permissao de escrita no CRM (`fam_pode_escrever()`),
-- a mesma trava de `anexos`. Nunca `USING (true)` para `public`: `public`
-- inclui `anon`, e a chave publica do bundle passaria.
alter table public.casos             enable row level security;
alter table public.caso_documentos   enable row level security;
alter table public.caso_itens        enable row level security;
alter table public.caso_item_catalogo enable row level security;

drop policy if exists casos_leitura on public.casos;
create policy casos_leitura on public.casos
  for select to authenticated using (true);
drop policy if exists casos_escrita on public.casos;
create policy casos_escrita on public.casos
  for all to authenticated using (fam_pode_escrever()) with check (fam_pode_escrever());

drop policy if exists caso_documentos_leitura on public.caso_documentos;
create policy caso_documentos_leitura on public.caso_documentos
  for select to authenticated using (true);
drop policy if exists caso_documentos_escrita on public.caso_documentos;
create policy caso_documentos_escrita on public.caso_documentos
  for all to authenticated using (fam_pode_escrever()) with check (fam_pode_escrever());

drop policy if exists caso_itens_leitura on public.caso_itens;
create policy caso_itens_leitura on public.caso_itens
  for select to authenticated using (true);
drop policy if exists caso_itens_escrita on public.caso_itens;
create policy caso_itens_escrita on public.caso_itens
  for all to authenticated using (fam_pode_escrever()) with check (fam_pode_escrever());

drop policy if exists caso_item_catalogo_leitura on public.caso_item_catalogo;
create policy caso_item_catalogo_leitura on public.caso_item_catalogo
  for select to authenticated using (true);
drop policy if exists caso_item_catalogo_escrita on public.caso_item_catalogo;
create policy caso_item_catalogo_escrita on public.caso_item_catalogo
  for all to authenticated using (fam_gerencia_usuarios()) with check (fam_gerencia_usuarios());

-- ── 5. atualizado_em ────────────────────────────────────────────────────────
create or replace function public.casos_toca_atualizado_em()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  new.atualizado_em := now();
  return new;
end $$;

drop trigger if exists casos_atualizado_em on public.casos;
create trigger casos_atualizado_em before update on public.casos
  for each row execute function public.casos_toca_atualizado_em();

-- ── 6. `anexos` passa a aceitar o caso ──────────────────────────────────────
-- O arquivo continua num lugar so no CRM. Assim, quando a triagem conclui e o
-- tomador nasce, o documento que veio no e-mail ja esta no acervo de anexos e
-- pode seguir para a ficha do tomador em vez de virar uma segunda pilha.
alter table public.anexos drop constraint if exists anexos_entidade_tipo_check;
alter table public.anexos add constraint anexos_entidade_tipo_check
  check (entidade_tipo = any (array['tomador'::text,'operacao'::text,'corretora'::text,'caso'::text]));

-- ── 7. Teto de arquivo ──────────────────────────────────────────────────────
-- O bucket estava em 5 MB, e pacote de documentos de tomador real passa disso
-- (ha PDF de 12 MB no acervo). Sem isto, a triagem falha no primeiro caso.
update storage.buckets set file_size_limit = 52428800 where id = 'fam-anexos';
